# Generated by Django 4.1.7 on 2023-07-20 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.IntegerField()),
                ('breed', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
